# rt_rules.conf - Revolutionary Technology ModSec3 Payload
# Example Custom Rule Engine Block
SecRule ARGS:test_attack "attack" "id:9000001,phase:2,deny,status:403,log,msg:'RT Vendor Security Block'"
